HELENGINE_CORE_CPP_ROOT ?=
HELENGINE_PSP_ISOLATED_BOOT ?= ON
HELENGINE_PSP_ENABLE_RUNTIME_STARTUP ?= OFF
HELENGINE_PSP_ENABLE_BOOT_TRACE ?= OFF
HELENGINE_PSP_ENABLE_RENDER_PROFILER ?= OFF

ifeq ($(strip $(HELENGINE_CORE_CPP_ROOT)),)
$(error HELENGINE_CORE_CPP_ROOT must point at the generated helengine.core C++ output folder)
endif

BUILD_DIR := build
TARGET_PBP := $(BUILD_DIR)/EBOOT.PBP
CMAKE_ARGS := -DHELENGINE_CORE_CPP_ROOT=$(HELENGINE_CORE_CPP_ROOT) -DHELENGINE_PSP_ISOLATED_BOOT=$(HELENGINE_PSP_ISOLATED_BOOT) -DHELENGINE_PSP_ENABLE_RUNTIME_STARTUP=$(HELENGINE_PSP_ENABLE_RUNTIME_STARTUP) -DHELENGINE_PSP_ENABLE_BOOT_TRACE=$(HELENGINE_PSP_ENABLE_BOOT_TRACE) -DHELENGINE_PSP_ENABLE_RENDER_PROFILER=$(HELENGINE_PSP_ENABLE_RENDER_PROFILER)

.PHONY: all clean

all: $(TARGET_PBP)

$(BUILD_DIR)/CMakeCache.txt: CMakeLists.txt
	@mkdir -p $(BUILD_DIR)
	cd $(BUILD_DIR) && psp-cmake $(CMAKE_ARGS) ..

$(TARGET_PBP): $(BUILD_DIR)/CMakeCache.txt
	$(MAKE) -C $(BUILD_DIR)

clean:
	@rm -rf $(BUILD_DIR)
